name: dart_crypto
description: Crypto benchmarks for dart
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  at_chops:
  atsdk_ffi:
  webcrypto: ^0.5.7
  hex: ^0.2.0
  crypto: ^3.0.5
  encrypt: ^5.0.3
  chalk: ^1.2.1
  cryptography: ^2.7.0
  better_cryptography: ^1.0.0+1
  path: ^1.9.1
  ffi: ^2.1.3

dependency_overrides:
  at_chops:
    path: ../../modules/dart/at_libraries/packages/at_chops
  atsdk_ffi:
    path: ../../ffi/dart

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
