name: at_mono

packages:
  - modules/dart/*/packages/*
  # at_libraries
  - modules/dart/at_libraries/at_*
  - modules/dart/at_libraries/base2e15
  - modules/dart/at_libraries/dart_utf7
  - modules/dart/at_libraries/redis-dart
  # at_tools
  - modules/dart/at_tools/at_*

scripts:
  update: |
    for i in $(ls modules/* | sed "s/,/ /g" | grep -v -e ":" -e "^$"); do
      git submodule update --init --remote -- "modules/$i"
    done;
  postupdate: melos bootstrap
