name: at_mono

packages:
  - modules/*/packages/*
  # at_libraries
  - modules/at_libraries/at_*/*
  - modules/at_libraries/base2e15/*
  - modules/at_libraries/dart_utf7/*
  - modules/at_libraries/redis-dart/*
  # at_tools
  - modules/at_tools/at_*/*

scripts:
  update: |
    REPOS="at_server,at_client_sdk,at_libraries,at_widgets,at_tools,at_app,at_services"
    for i in $(echo $REPOS | sed "s/,/ /g"); do
      git submodule update --init --remote -- "modules/$i"
    done;
  postupdate: melos bootstrap
