name: Update submodules
description: Update all submodules in this repository

runs:
  using: composite
  steps:
    - name: Update modules
      shell: bash
      env:
        TOKEN: ${{ github.token }}
      run: |
        for i in $(git submodule status | awk 'sub(/^ */, "")' | awk -F ' ' '{print($2)}'); do
          echo "updating module $i"
          git submodule update --init --remote -- "$i"
        done;
