name: Update submodules
description: Update all submodules in this repository

runs:
  using: composite
  steps:
    - name: Update dart modules
      shell: bash
      env:
        TOKEN: ${{ github.token }}
      # Update each in parallel
      # Then wait on each process id to ensure all updates are completed before moving on
      run: |
        DART_MODULES="at_server,at_client_sdk,at_libraries,at_widgets,at_tools"
        for i in ${DART_MODULES//,/ }; do
          git submodule update --init --remote -- "modules/dart/$i"
        done;
