name: Update submodules
description: Update all submodules in this repository

runs:
  using: composite
  steps:
    - name: Update modules
      shell: bash
      env:
        MODULE: ${{ inputs.module }}
        TOKEN: ${{ github.token }}
      # Update each in parallel
      # Then wait on each process id to ensure all updates are completed before moving on
      run: |
        REPOS="at_server,at_client_sdk,at_libraries,at_widgets,at_tools,at_app,at_services"
        for i in $(echo $REPOS | sed "s/,/ /g"); do
          git submodule update --init --remote -- "modules/$i"
        done;
