name: Update Diagrams
description: Update the diagrams

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - uses: ts-graphviz/setup-graphviz@v1

    - name: Run melos analysis
      shell: bash
      env:
        TMP: ${{ runner.temp }}
      run: |
        dart pub global activate melos
        dart pub global run melos ls -r --json -l --ignore='*example*' >> "$TMP/melos-json.json"
        dart pub global run melos ls -r --graph --ignore='*example*' >> "$TMP/melos-graph.json"
        dart pub global run melos ls -r --gviz --ignore='*example*' >> "$TMP/melos-gviz.gv"

    - name: Execute diagram generator
      shell: bash
      env:
        TMP: ${{ runner.temp }}
      run: |
        chmod +w ./docs/diagrams/*
        pip install -r ./tools/package_diagrams.requirements.txt
        python ./tools/package_diagrams.py "$TMP/melos-gviz.gv" "$GITHUB_WORKSPACE/docs/diagrams"

    - name: Auto commit diagrams
      uses: stefanzweifel/git-auto-commit-action@v4
      id: commit_id
      with:
        commit_message: 'docs(ci): Update docs'
