name: Update Diagrams
description: Update the diagrams

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - shell: bash
      run: |
        pip install -r ./analysis/requirements.txt
        python ./analysis/package_tree.py

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}

    - name: Auto commit diagrams
      uses: stefanzweifel/git-auto-commit-action@v4
      id: commit_id
      with:
        commit_message: 'docs(ci): Update docs'