name: atsdk_ffi
description: ffi bindings for the atsdk
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^15.0.0
  lints: ^4.0.0
  test: ^1.24.0

ffigen:
  name: AtSdkFfi
  description: Bindings to atsdk in C
  output:
    bindings: lib/src/bindings.g.dart
  headers:
    entry-points:
      - ../../modules/c/at_c/packages/atchops/include/**.h
      - ../../modules/c/at_c/packages/atlogger/include/**.h
    include-directives:
      - ../../modules/c/at_c/packages/atchops/include/**.h
      - ../../modules/c/at_c/packages/atlogger/include/**.h
  compiler-opts-automatic:
    macos:
      include-c-standard-library: true
  include-unused-typedefs: true # We may be implicitly using them in places

