name: Get melos cache
description: Retrieve the cached pub packages from melos bootstrap

inputs:
  build_id:
    required: true
    description: The id of the build

runs:
  using: composite
  steps:
    - name: Retrieve lock file cache
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: '**/pubspec.lock'
        key: ${{ inputs.build_id }}

    - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225 #v2.12.0
      with:
        channel: 'stable'
        cache: true
        cache-key: ${{ inputs.build_id }}
