name: Generate Build Id
description: Generates a build id

outputs:
  build_id:
    description: The id of the build
    value: ${{ steps.build.outputs.build_id }}

runs:
  using: composite
  steps:
    - name: Set build id
      shell: bash
      id: build
      env:
        GENERATED_ID: ${{ format('{0}', github.run_id) }}
      run: |
        echo "build_id=$GENERATED_ID" >> $GITHUB_OUTPUT
