name: Analysis

on:
  workflow_dispatch:
  pull_request:

jobs:
  package_tree:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/update-diagrams
