name: Analysis

on:
  workflow_dispatch:
  pull_request:

jobs:
  packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/composite/update-diagrams
