name: Integration Tests

on:
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    outputs:
      commit_ref: ${{ steps.build.outputs.commit_ref }}
      build_id: ${{ steps.build.outputs.build_id }}

    if: ${{ github.repository == 'atsign-foundation/at_mono' }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Generate build id
        id: build
        uses: ./.github/composite/build-id

      - name: Bootstrap
        uses: ./.github/composite/melos-bootstrap
        with:
          build_id: ${{ steps.build.outputs.build_id }}

  at_server_sanity_check:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ needs.build.outputs.commit_ref }}
          submodules: recursive

      - name: Retrieve melos cache
        uses: ./.github/composite/get-melos-cache
        with:
          build_id: ${{ needs.build.outputs.build_id }}

      - name: "Lockfile Sanity Check"
        run: |
          cat ./modules/at_client_sdk/at_client/pubspec.lock | grep -A 6 "at_commons:"
