name: Update Modules
on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        required: true
        description: The module(s) to update
        options:
          - all
          - at_server
          - at_client_sdk
          - at_libraries
          - at_widgets
          - at_tools

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        id: build
        uses: ./.github/composite/build
        with:
          module: ${{ github.event.inputs.module }}